name: Upload and Host on S3

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    -  name: Checkout
    -  uses: actions/checkout@v4
    
    -  name: AWS Configure
    -  uses: actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    -  name: Syncing files from repo to bucket and deployment
       run: aws s3 sync s3://tada01 --delete
