name: Upload and Host on S3

# on: workflow_dispatch
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
permissions:
  issues: write
    
jobs:
  build-main:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    # - name: Approval
    #   uses: trstringer/manual-approval@v1
    #   with:
    #     secret: ${{ secrets.GITHUB_TOKEN }}
    #     approvers: maulik-wmp
    #     minimum-approvals: 1
    #     issue-title: "Deploying v1.3.5 to prod from staging"
    #     issue-body: "Please approve or deny the deployment of version v1.3.5."
    #     exclude-workflow-initiator-as-approver: false
    #     additional-approved-words: ''
    #     additional-denied-words: ''

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Syncing files from repo to bucket and deployment
      run: aws s3 sync . s3://actions-express-main --delete

  build-dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}

    steps:
    - name: Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: maulik-wmp
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to dev from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Syncing files from repo to bucket and deployment
      run: aws s3 sync . s3://actions-express-dev --delete

  create-tags:
    name: Tags
    needs: build-main
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure git identity
        run: |
          git config --global user.email "maulikpandey@wingmanpartners.com"
          git config --global user.name "maulik-wmp"

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
  
      - name: Check if tag exists
        run: |
          if git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
            echo "Tag v${{ steps.get_version.outputs.version }} already exists"
          fi
  
      - name: Remove existing tag if exists
        run: |
          if git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
            git push --delete origin v${{ steps.get_version.outputs.version }}
            git tag -d v${{ steps.get_version.outputs.version }}
          fi
  
      - name: Create tag
        run: |
          git tag -a v${{ steps.get_version.outputs.version }} -m "Version ${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}
