name: Upload and Host on S3

on: 
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    
jobs:
  build-main:

    runs-on: ubuntu-latest

    steps:
    -  name: Approval
       uses: macnev2013/manual-approval@latest
       with:
        approvers: maulik-wmp
        minimum-approvals: 1
        issue-title: 'Manual Approval'
        issue-body: |
          "Issue Body"
          
    -  name: Checkout
       uses: actions/checkout@v4
    
    -  name: AWS Configure
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    -  name: Syncing files from repo to bucket and deployment
       run: aws s3 sync . s3://actions-express-main --delete
    
    if: ${{ github.ref == 'refs/heads/main'}}
  

  build-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    -  name: AWS Configure
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    -  name: Syncing files from repo to bucket and deployment
       run: aws s3 sync . s3://actions-express-dev --delete
    
    if: ${{ github.ref == 'refs/heads/dev'}}
